In [1]:
from Bio.Cluster import kcluster
import numpy as np
sequences = [
    'ATCGTCGGAATCCCA',
    'ATCGTCGGAATTCCA',
    'ATACTCGGAATCCCA',
    'ATCTTCGGAATCCCA'
    ]
matrix = np.asarray([np.frombuffer(bytes(s,'UTF-8'), dtype=np.uint8) for s in sequences])
clusterid, error, nfound = kcluster(matrix)
print(clusterid)

[0 1 0 1]


In [2]:
matrix

array([[65, 84, 67, 71, 84, 67, 71, 71, 65, 65, 84, 67, 67, 67, 65],
       [65, 84, 67, 71, 84, 67, 71, 71, 65, 65, 84, 84, 67, 67, 65],
       [65, 84, 65, 67, 84, 67, 71, 71, 65, 65, 84, 67, 67, 67, 65],
       [65, 84, 67, 84, 84, 67, 71, 71, 65, 65, 84, 67, 67, 67, 65]],
      dtype=uint8)

In [3]:
from Bio.Cluster import kmedoids
from Bio.Cluster import distancematrix
distance = distancematrix(matrix)
clusterid, error, nfound = kmedoids(distance)
print(clusterid)

[0 1 0 0]


In [4]:
distance

[array([], dtype=float64),
 array([19.26666667]),
 array([ 1.33333333, 20.6       ]),
 array([11.26666667, 30.53333333, 19.53333333])]

In [5]:
from Bio.Cluster import treecluster
tree = treecluster(matrix)

In [7]:
print(tree)

(2, 0): 1.33333
(3, -1): 19.5333
(1, -2): 30.5333


In [8]:
from Bio.Cluster import somcluster
clusterid, celldata = somcluster(matrix)
print(clusterid)

[[1 0]
 [1 0]
 [1 0]
 [0 0]]
